version: "3.9"

services:
  db:
    image: postgres:15-alpine
    container_name: db
    restart: unless-stopped
    env_file:
      - .env.docker
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-appdb}
      POSTGRES_USER: ${POSTGRES_USER:-appuser}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-apppassword}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "appuser", "-d", "appdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: api
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.docker
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-appuser}:${POSTGRES_PASSWORD:-apppassword}@db:5432/${POSTGRES_DB:-appdb}
      NODE_ENV: ${NODE_ENV:-development}
    volumes:
      - uploads:/app/uploads
      - logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  core:
    build:
      context: .
      dockerfile: Dockerfile.consciousness
    container_name: core
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env.docker
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER:-appuser}:${POSTGRES_PASSWORD:-apppassword}@db:5432/${POSTGRES_DB:-appdb}
      NODE_ENV: ${NODE_ENV:-development}
    volumes:
      - uploads:/app/uploads
      - logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 10s
      timeout: 5s
      retries: 5

  web:
    build:
      context: .
      dockerfile: Dockerfile.ui
    container_name: web
    restart: unless-stopped
    depends_on:
      api:
        condition: service_healthy
      core:
        condition: service_healthy
    env_file:
      - .env.docker
    environment:
      NODE_ENV: ${NODE_ENV}
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:4173/"]
      interval: 10s
      timeout: 5s
      retries: 5

  proxy:
    image: caddy:2-alpine
    container_name: proxy
    restart: unless-stopped
    env_file:
      - .env.docker
    depends_on:
      web:
        condition: service_healthy
      core:
        condition: service_healthy
    ports:
      - "80:80"
      - "443:443"
    environment:
      - CADDY_MAINTENANCE=${CADDY_MAINTENANCE:-off}
    volumes:
      - ./Caddyfile.docker:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "${PROMETHEUS_PORT:-9090}:9090"

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    restart: unless-stopped
    ports:
      - "3001:3000"
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GRAFANA_ADMIN_PASSWORD:-admin}
    volumes:
      - ./prometheus/grafana-provisioning/:/etc/grafana/provisioning/

volumes:
  postgres_data:
  uploads:
  logs:
  caddy_data:
  caddy_config: