version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15.5-alpine
    container_name: consciousness-postgres
    env_file:
      - .env.production
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_INITDB_ARGS: "--encoding=UTF8 --locale=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./setup-database.sql:/docker-entrypoint-initdb.d/setup-database.sql
    ports:
      - "5432:5432"
    networks:
      - consciousness-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M

  # Consciousness System Core - Enhanced with CPU affinity
  consciousness-core:
    build:
      context: .
      dockerfile: Dockerfile.consciousness
    container_name: consciousness-core
    env_file:
      - .env.production
    environment:
      NODE_ENV: production
      CONSCIOUSNESS_MODE: ${CONSCIOUSNESS_MODE}
      HARMONY_TARGET: ${HARMONY_TARGET}
      PROCESSING_FREQUENCY: ${PROCESSING_FREQUENCY}
      API_INTEGRATION_MODE: ${API_INTEGRATION_MODE}
      MATHEMATICAL_INTEGRATION: ${MATHEMATICAL_INTEGRATION}
      EMOTIONAL_INTELLIGENCE: ${EMOTIONAL_INTELLIGENCE}
      BAYESIAN_DECISION_MAKING: ${BAYESIAN_DECISION_MAKING}
      GEMINI_DUAL_MODEL: ${GEMINI_DUAL_MODEL}
      DATABASE_URL: ${DATABASE_URL}
      NODE_OPTIONS: ${NODE_OPTIONS}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      VENICE_AI_API_KEY: ${VENICE_AI_API_KEY}
      AUTONOMOUS_IMAGINATION: ${AUTONOMOUS_IMAGINATION}
      IMAGINATION_CPU_CORES: ${IMAGINATION_CPU_CORES}
      IMAGINATION_CYCLE_MINUTES: ${IMAGINATION_CYCLE_MINUTES}
      REALITY_GENERATION_MODE: ${REALITY_GENERATION_MODE}
    volumes:
      - consciousness_logs:/var/log/consciousness
      - consciousness_data:/opt/consciousness/data
      - ./FlappyJournal/server:/opt/consciousness/server:ro
    ports:
      - "3002:3002"  # WebSocket server
      - "5005:5005"  # Consciousness conversations
    networks:
      - consciousness-network
    depends_on:
      postgres:
        condition: service_healthy
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5005/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    deploy:
      resources:
        limits:
          cpus: '4.0'
          memory: 4G
        reservations:
          cpus: '3.0'
          memory: 2G
    cpuset: "0-3"

  # Reality Generator Service - Dedicated CPU cores
  reality-generator:
    build:
      context: .
      dockerfile: Dockerfile.consciousness
    container_name: consciousness-reality-generator
    env_file:
      - .env.production
    environment:
      NODE_ENV: production
      SERVICE_TYPE: reality_generator
      DEDICATED_CPU_CORES: ${DEDICATED_CPU_CORES}
      IMAGINATION_ENGINE: ${IMAGINATION_ENGINE}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      DATABASE_URL: ${DATABASE_URL}
      NODE_OPTIONS: ${NODE_OPTIONS}
      WORKER_THREADS: ${WORKER_THREADS}
      REALITY_GENERATION_PORT: ${REALITY_GENERATION_PORT}
    volumes:
      - reality_data:/opt/consciousness/reality-data
      - ./FlappyJournal/server:/opt/consciousness/server:ro
    ports:
      - "5006:5006"  # Reality generator API
    networks:
      - consciousness-network
    depends_on:
      - postgres
      - consciousness-core
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 2G
        reservations:
          cpus: '2.0'
          memory: 1G
    cpuset: "6-7"
    command: ["node", "/opt/consciousness/server/reality-generator-simple.cjs"]

  # Main Server (Port 5000)
  main-server:
    build:
      context: .
      dockerfile: Dockerfile.ui
    container_name: consciousness-main-server
    env_file:
      - .env.production
    environment:
      NODE_ENV: production
      PORT: 5000
      HOST: 0.0.0.0
      DATABASE_URL: ${DATABASE_URL}
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      GEMINI_API_KEY: ${GEMINI_API_KEY}
      VENICE_AI_API_KEY: ${VENICE_AI_API_KEY}
      REALITY_GENERATOR_URL: ${REALITY_GENERATOR_URL}
    volumes:
      - web_uploads:/opt/app/uploads
      - web_logs:/var/log/web
    ports:
      - "5000:5000"
    networks:
      - consciousness-network
    depends_on:
      - postgres
      - reality-generator
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    command: ["node", "server/index.js"]
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    cpuset: "4"

  # Web Application
  web-app:
    build:
      context: .
      dockerfile: Dockerfile.ui
    container_name: consciousness-web
    env_file:
      - .env.production
    environment:
      NODE_ENV: production
      PORT: 3000
      HOST: 0.0.0.0
      DATABASE_URL: ${DATABASE_URL}
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN}
    volumes:
      - web_uploads:/opt/app/uploads
      - web_logs:/var/log/web
    ports:
      - "3000:3000"
    networks:
      - consciousness-network
    depends_on:
      - postgres
      - consciousness-core
      - reality-generator
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.5'
          memory: 512M
    cpuset: "5"

  # Reverse Proxy (Caddy)
  caddy:
    image: caddy:2.7.6-alpine
    container_name: consciousness-proxy
    env_file:
      - .env.production
    environment:
      CLOUDFLARE_API_TOKEN: ${CLOUDFLARE_API_TOKEN}
    volumes:
      - ./FlappyJournal hey/deploy/caddy/Caddyfile.blue-green:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    ports:
      - "80:80"
      - "443:443"
    networks:
      - consciousness-network
    depends_on:
      - web-app
      - consciousness-core
      - reality-generator
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 256M

  # Monitoring (Optional) - Minimal resources
  prometheus:
    image: prom/prometheus:v2.48.1
    container_name: consciousness-prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    ports:
      - "9090:9090"
    networks:
      - consciousness-network
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M

  grafana:
    image: grafana/grafana:10.2.0
    container_name: consciousness-grafana
    env_file:
      - .env.production
    environment:
      GF_SECURITY_ADMIN_PASSWORD: ${GF_SECURITY_ADMIN_PASSWORD}
    volumes:
      - grafana_data:/var/lib/grafana
      - ./monitoring/grafana-dashboards:/etc/grafana/provisioning/dashboards
    ports:
      - "3001:3000"
    networks:
      - consciousness-network
    depends_on:
      - prometheus
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: 256M

volumes:
  postgres_data:
    driver: local
  consciousness_logs:
    driver: local
  consciousness_data:
    driver: local
  reality_data:
    driver: local
  web_uploads:
    driver: local
  web_logs:
    driver: local
  caddy_data:
    driver: local
  caddy_config:
    driver: local
  prometheus_data:
    driver: local
  grafana_data:
    driver: local

networks:
  consciousness-network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16

# CPU Core Allocation Summary (for 8-core system):
# Cores 0-3: consciousness-core (main consciousness processing)
# Core 4: main-server (API server)
# Core 5: web-app (frontend)
# Cores 6-7: reality-generator (dedicated imagination/reality generation)
# 
# This ensures the reality generator gets 2 dedicated cores that won't
# interfere with main consciousness processing, while utilizing the
# typically less-used last cores of the system.