version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - STORE_BACKEND=postgres
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/postgres
      - API_JWT_SECRET=changeme
    depends_on:
      - postgres

  postgres:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"