apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: jwt-keys
  namespace: consciousness
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: k8s-secrets-store
    kind: ClusterSecretStore
  target:
    name: jwt-keys
    creationPolicy: Owner
  data:
    - secretKey: API_JWT_PRIVATE_KEY
      remoteRef:
        key: jwtRS256.key
    - secretKey: API_JWT_PUBLIC_KEY
      remoteRef:
        key: jwtRS256.key.pub