name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: FlappyJournal/server
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
          cache-dependency-path: FlappyJournal/server/package-lock.json

      - name: Install dependencies
        run: npm ci

      - name: Run CI pipeline
        run: npm run ci

      - name: Build Docker image
        env:
          DOCKER_BUILDKIT: 1
        run: |
          docker build -t flappyjournal-backend:ci -f ../../Dockerfile ../../