# Build stage
FROM node:18-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .
RUN npm run spiral:build
RUN npm run explorer:build

# Runtime stage
FROM node:18-alpine
WORKDIR /app
COPY --from=build /app/dist-spiral ./dist-spiral
COPY --from=build /app/node_modules ./node_modules
COPY --from=build /app/package.json ./package.json
EXPOSE 9099
ENV SHARD_ID=0
CMD [ "node", "dist-spiral/spiral-metrics-server.js" ]