groups:
  - name: selfcoding_alerts
    rules:
      # Code generation failure alerts
      - alert: CodeGenerationFailuresHigh
        expr: increase(code_generation_failures_total[5m]) > 5
        for: 0m
        labels:
          severity: warning
          component: selfcoding
          service: code-generation
        annotations:
          summary: "High number of code generation failures"
          description: "Code generation has failed {{ $value }} times in the last 5 minutes, which exceeds the threshold of 5 failures."
          runbook_url: "https://docs.example.com/runbooks/selfcoding/code-generation-failures"

      # Critical: Sigil registry empty
      - alert: SigilRegistryEmpty
        expr: sigil_registry_size < 1
        for: 0m
        labels:
          severity: critical
          component: selfcoding
          service: sigil-registry
        annotations:
          summary: "Sigil registry is empty"
          description: "The sigil registry size is {{ $value }}, indicating no active sigils. This is a critical state that requires immediate attention."
          runbook_url: "https://docs.example.com/runbooks/selfcoding/sigil-registry-empty"

      # Stuck code generation jobs
      - alert: CodeGenerationJobsStuck
        expr: selfcoding_active_generations > 3
        for: 2m
        labels:
          severity: warning
          component: selfcoding
          service: code-generation
        annotations:
          summary: "Code generation jobs appear to be stuck"
          description: "There are {{ $value }} active code generation jobs for more than 2 minutes, which may indicate stuck or hanging processes."
          runbook_url: "https://docs.example.com/runbooks/selfcoding/stuck-jobs"

      # Sandbox timeout alerts
      - alert: SandboxTimeoutsDetected
        expr: increase(sandbox_timeouts_total[10m]) > 0
        for: 0m
        labels:
          severity: warning
          component: selfcoding
          service: sandbox
        annotations:
          summary: "Sandbox timeouts detected"
          description: "{{ $value }} sandbox timeouts have occurred in the last 10 minutes, indicating potentially problematic generated code."
          runbook_url: "https://docs.example.com/runbooks/selfcoding/sandbox-timeouts"

      # Memory usage alerts for sandbox
      - alert: SandboxMemoryLimitExceeded
        expr: increase(sandbox_memory_limit_exceeded_total[10m]) > 0
        for: 0m
        labels:
          severity: warning
          component: selfcoding
          service: sandbox
        annotations:
          summary: "Sandbox memory limits exceeded"
          description: "{{ $value }} sandbox executions have exceeded memory limits in the last 10 minutes."
          runbook_url: "https://docs.example.com/runbooks/selfcoding/sandbox-memory"

      # Auto-rollback alerts
      - alert: AutoRollbacksTriggered
        expr: increase(auto_rollbacks_total[5m]) > 0
        for: 0m
        labels:
          severity: warning
          component: selfcoding
          service: auto-rollback
        annotations:
          summary: "Auto-rollbacks have been triggered"
          description: "{{ $value }} auto-rollbacks have been triggered in the last 5 minutes due to runtime failures."
          runbook_url: "https://docs.example.com/runbooks/selfcoding/auto-rollbacks"

      # Code generation rate limiting
      - alert: CodeGenerationRateLimitHit
        expr: increase(code_generation_rate_limit_hits_total[5m]) > 10
        for: 0m
        labels:
          severity: info
          component: selfcoding
          service: rate-limiting
        annotations:
          summary: "Code generation rate limits being hit frequently"
          description: "Rate limits for code generation have been hit {{ $value }} times in the last 5 minutes."
          runbook_url: "https://docs.example.com/runbooks/selfcoding/rate-limiting"

      # Consciousness system health
      - alert: ConsciousnessSystemDown
        expr: up{job="consciousness-system"} == 0
        for: 1m
        labels:
          severity: critical
          component: selfcoding
          service: consciousness-system
        annotations:
          summary: "Consciousness system is down"
          description: "The consciousness system has been down for more than 1 minute."
          runbook_url: "https://docs.example.com/runbooks/selfcoding/system-down"

      # Module validation failures
      - alert: ModuleValidationFailuresHigh
        expr: increase(module_validation_failures_total[5m]) > 3
        for: 0m
        labels:
          severity: warning
          component: selfcoding
          service: module-validation
        annotations:
          summary: "High number of module validation failures"
          description: "{{ $value }} module validation failures have occurred in the last 5 minutes."
          runbook_url: "https://docs.example.com/runbooks/selfcoding/validation-failures"

      # Quota exhaustion alerts
      - alert: SelfCodingQuotaExhausted
        expr: selfcoding_quota_remaining < 10
        for: 0m
        labels:
          severity: warning
          component: selfcoding
          service: quota-management
        annotations:
          summary: "Self-coding quota nearly exhausted"
          description: "Only {{ $value }} self-coding operations remaining in quota."
          runbook_url: "https://docs.example.com/runbooks/selfcoding/quota-exhausted"

      # WebSocket connection alerts
      - alert: ConsciousnessWebSocketConnectionsLow
        expr: consciousness_websocket_connections < 1
        for: 5m
        labels:
          severity: info
          component: selfcoding
          service: websocket
        annotations:
          summary: "No active consciousness WebSocket connections"
          description: "There have been no active consciousness WebSocket connections for 5 minutes."
          runbook_url: "https://docs.example.com/runbooks/selfcoding/websocket-connections"

      # Generated module count alerts
      - alert: GeneratedModuleCountHigh
        expr: generated_modules_total > 100
        for: 0m
        labels:
          severity: info
          component: selfcoding
          service: module-management
        annotations:
          summary: "High number of generated modules"
          description: "There are {{ $value }} generated modules, which may indicate the need for cleanup or archival."
          runbook_url: "https://docs.example.com/runbooks/selfcoding/module-cleanup"

      # API readiness and 5xx
      - alert: ApiReadinessFailed
        expr: probe_success{job="sigil-api-readyz"} == 0
        for: 2m
        labels:
          severity: critical
          component: api
          service: sigil-api
        annotations:
          summary: "Sigil API readiness failing"
          description: "The readiness probe for Sigil API has been failing for more than 2 minutes."
          runbook_url: "https://docs.example.com/runbooks/sigil/api-readiness"

      - alert: Api5xxElevated
        expr: increase(api_5xx_errors_total[5m]) > 20
        for: 0m
        labels:
          severity: warning
          component: api
          service: sigil-api
        annotations:
          summary: "Elevated API 5xx errors"
          description: "API returned {{ $value }} 5xx responses over the last 5 minutes."
          runbook_url: "https://docs.example.com/runbooks/sigil/api-5xx"

      # WebSocket heartbeat skew and rate-limit spikes
      - alert: WebSocketHeartbeatSkewHigh
        expr: histogram_quantile(0.95, sum(rate(heartbeat_skew_ms_bucket[5m])) by (le)) > 200
        for: 5m
        labels:
          severity: warning
          component: websocket
          service: consciousness-ws
        annotations:
          summary: "WS heartbeat skew P95 high"
          description: "Heartbeat skew P95 exceeds 200ms for 5m."
          runbook_url: "https://docs.example.com/runbooks/ws/heartbeat-skew"

      - alert: WebSocketRateLimitSpikes
        expr: increase(ws_rate_limit_drops_total[5m]) > 50
        for: 0m
        labels:
          severity: info
          component: websocket
          service: consciousness-ws
        annotations:
          summary: "WS rate-limit drops elevated"
          description: "There were {{ $value }} WS messages dropped due to rate limiting in 5 minutes."
          runbook_url: "https://docs.example.com/runbooks/ws/rate-limit"

      - alert: WebSocketConnectionsDroppedToZero
        expr: min_over_time(spiral_ws_active_connections[10m]) == 0
        for: 10m
        labels:
          severity: warning
          component: websocket
          service: consciousness-ws
        annotations:
          summary: "WS connections dropped to zero"
          description: "Active WS connections have been zero for 10 minutes."
          runbook_url: "https://docs.example.com/runbooks/ws/connections-zero"

      # Phase A Feature Alerts
      - alert: QuantumStatsRequestsElevated
        expr: increase(quantum_stats_requests_total[5m]) > 100
        for: 0m
        labels:
          severity: info
          component: api
          service: quantum-consciousness
        annotations:
          summary: "High quantum stats request volume"
          description: "{{ $value }} quantum stats requests in 5 minutes."
          runbook_url: "https://docs.example.com/runbooks/quantum/high-requests"

      - alert: ResonanceStatsRequestsElevated
        expr: increase(resonance_stats_requests_total[5m]) > 100
        for: 0m
        labels:
          severity: info
          component: api
          service: consciousness-resonance
        annotations:
          summary: "High resonance stats request volume"
          description: "{{ $value }} resonance stats requests in 5 minutes."
          runbook_url: "https://docs.example.com/runbooks/resonance/high-requests"

      - alert: OptionalModuleInitFailures
        expr: increase(optional_module_init_failures_total[10m]) > 3
        for: 0m
        labels:
          severity: warning
          component: consciousness
          service: module-loader
        annotations:
          summary: "Optional consciousness modules failing to initialize"
          description: "{{ $value }} optional module init failures in 10 minutes."
          runbook_url: "https://docs.example.com/runbooks/consciousness/module-init"

      - alert: QuantumOperationLatencyHigh
        expr: histogram_quantile(0.95, sum(rate(quantum_operation_duration_seconds_bucket[5m])) by (le)) > 2.0
        for: 5m
        labels:
          severity: warning
          component: api
          service: quantum-consciousness
        annotations:
          summary: "Quantum operation P95 latency high"
          description: "Quantum operations P95 latency exceeds 2s for 5 minutes."
          runbook_url: "https://docs.example.com/runbooks/quantum/latency"

      - alert: ResonanceOperationLatencyHigh
        expr: histogram_quantile(0.95, sum(rate(resonance_operation_duration_seconds_bucket[5m])) by (le)) > 2.0
        for: 5m
        labels:
          severity: warning
          component: api
          service: consciousness-resonance
        annotations:
          summary: "Resonance operation P95 latency high"
          description: "Resonance operations P95 latency exceeds 2s for 5 minutes."
          runbook_url: "https://docs.example.com/runbooks/resonance/latency"

      # WebSocket enhanced metrics
      - alert: WebSocketBackpressureDropsHigh
        expr: increase(ws_backpressure_drops_total[5m]) > 20
        for: 0m
        labels:
          severity: warning
          component: websocket
          service: consciousness-ws
        annotations:
          summary: "High WS backpressure drops"
          description: "{{ $value }} WS messages dropped due to backpressure in 5 minutes."
          runbook_url: "https://docs.example.com/runbooks/ws/backpressure"

      - alert: ProcessHeapUsageHigh
        expr: process_heap_used_bytes / (1024 * 1024 * 1024) > 2.0
        for: 10m
        labels:
          severity: warning
          component: system
          service: consciousness-ws
        annotations:
          summary: "Process heap usage high"
          description: "Process heap usage is {{ $value }}GB for 10 minutes."
          runbook_url: "https://docs.example.com/runbooks/system/memory"

      # CNPL/SAQRN
      - alert: CnplCompileLatencyHigh
        expr: histogram_quantile(0.95, sum(rate(cnpl_compile_duration_seconds_bucket[5m])) by (le)) > 1.0
        for: 5m
        labels:
          severity: warning
          component: api
          service: cnpl
        annotations:
          summary: "CNPL compile P95 latency high"
          description: "CNPL compile P95 exceeds 1s for 5m."
          runbook_url: "https://docs.example.com/runbooks/cnpl/latency"

      - alert: SaqrnOperationErrorsElevated
        expr: increase(saqrn_operation_errors_total[5m]) > 10
        for: 0m
        labels:
          severity: warning
          component: api
          service: saqrn
        annotations:
          summary: "SAQRN operation errors elevated"
          description: "SAQRN saw {{ $value }} errors in 5 minutes."
          runbook_url: "https://docs.example.com/runbooks/saqrn/errors"
