replicaCount: 1

image:
  repository: ghcr.io/example/holo-generator
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 3000

# Environment variables for the application
env:
  NATS_URL: nats://nats:4222
  LOG_LEVEL: info

# Resources for the container
resources: {}

# Horizontal Pod Autoscaler settings
hpa:
  enabled: true
  minReplicas: 1
  maxReplicas: 5
  cpu: 70
  jetstreamLag: 5000
