apiVersion: litmuschaos.io/v1alpha1
kind: ChaosEngine
metadata:
  name: holograph-db-loss
  namespace: default
spec:
  appinfo:
    appns: default
    applabel: app=holograph-db
    appkind: statefulset
  chaosServiceAccount: litmus-admin
  experiments:
    - name: pod-delete
      spec:
        components:
          env:
            - name: TOTAL_CHAOS_DURATION
              value: '30'
            - name: CHAOS_INTERVAL
              value: '10'
