const WebSocket = require('ws');
const fs = require('fs');
const token = fs.readFileSync('/tmp/jwt_ws.txt','utf8').trim();
const path = process.argv[2] || '/health-stream';
const url='wss://api.featherweight.world'+path;
const ws=new WebSocket(url,{rejectUnauthorized:true, headers:{'Sec-WebSocket-Protocol': token}});
let opened=false;
ws.on('open',()=>{opened=true;console.log('OPEN', path);});
ws.on('message',m=>{console.log('MSG', path, m.toString().slice(0,160)); ws.close();});
ws.on('error',e=>{console.log('ERR', path, e.message); process.exit(2);});
ws.on('close',()=>{console.log('CLOSE', path); process.exit(0);});
