{
 "title": "Postgres Overview",
 "tags": [
  "postgres",
  "database"
 ],
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Postgres Connections",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 0 },
   "targets": [
    { "expr": "pg_connections", "legendFormat": "Connections" }
   ]
  },
  {
   "title": "Commits",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_commit[5m])",
     "legendFormat": "Commits"
    }
   ]
  },
  {
   "title": "Rollbacks",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "targets": [
    {
     "expr": "rate(pg_stat_database_xact_rollback[5m])",
     "legendFormat": "Rollbacks"
    }
   ]
  }
 ]
}