name: build-push-sign

on:
  push:
    branches: [ main ]
  push:
    tags:
      - 'v*.*.*'

jobs:
  build-push-sign:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
      packages: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push images (multi-arch)
        env:
          REPO: ghcr.io/${{ github.repository }}
        run: |
          for df in Dockerfile Dockerfile.api Dockerfile.ui; do
            name=$(basename "$df" | sed 's/Dockerfile//;s/\.//g' | tr '[:upper:]' '[:lower:]')
            # fallback: Dockerfile -> core, Dockerfile.api -> api, Dockerfile.ui -> ui
            [ "$name" = "" ] && name="core"
            docker buildx build \
              --platform linux/amd64,linux/arm64 \
              -f "$df" \
              -t "$REPO:$name-${GITHUB_SHA}" \
              -t "$REPO:$name-latest" \
              --push .
          done

      - name: Install cosign
        uses: sigstore/cosign-installer@v3.4.0

      - name: Sign container images with cosign and GitHub OIDC
        env:
          REPO: ghcr.io/${{ github.repository }}
        run: |
          for name in core api ui; do
            for tag in "${name}-${GITHUB_SHA}" "${name}-latest"; do
              cosign sign --yes "$REPO:$tag"
            done
          done