name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 3 * * 1'  # Weekly, Monday at 3am UTC

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Install Trivy
        uses: aquasecurity/trivy-action@master
        with:
          cache: true

      - name: Trivy config scan on Dockerfiles and source
        run: |
          trivy fs --exit-code 1 --severity HIGH,CRITICAL .

      - name: Build root Dockerfile image
        run: docker build -f Dockerfile -t test-image .

      - name: Trivy image scan (root Dockerfile)
        run: trivy image --exit-code 1 --severity HIGH,CRITICAL test-image

  compose-health:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        compose:
          - docker-compose.api.yml
          - docker-compose.consciousness.yml
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Integration and health test
        run: |
          chmod +x scripts/compose-health-check.sh
          bash scripts/compose-health-check.sh "${{ matrix.compose }}"