name: Docker Security CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  trivy-scan:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout     node-version: 20
      - run: npm ci
      - run: npm run test:ci
      - run: npm audit --audit-level=high || true