name: Nightly Heavy Tests

on:
  schedule:
    - cron: '0 2 * * *'  # Run at 2 AM UTC daily
  workflow_dispatch:  # Allow manual trigger

jobs:
  nightly_heavy:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run heavy tests with full coverage
        run: npm run test:coverage:heavy
        env:
          RUN_HEAVY_TESTS: '1'
      - name: Verify coverage threshold
        run: npm run verify-coverage
      - name: Upload coverage reports
        uses: codecov/codecov-action@v3
        with:
          file: ./coverage/lcov.info
          flags: nightly
          name: codecov-nightly
      - name: Archive test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: nightly-test-results
          path: |
            coverage/
            test-results.xml
      - name: Notify on failure
        if: failure()
        uses: 8398a7/action-slack@v3
        with:
          status: failure
          text: 'Nightly heavy tests failed! Check the logs.'
        env:
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}